name: badiboss_eglise
description: Badiboss Eglise
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Versions compatibles avec Dart 3.2.x (on évite >=3.3)
  http: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  share_plus: ^7.2.2
  mobile_scanner: ^3.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # ✅ Icône app (Android/Windows/Web)
  flutter_launcher_icons: ^0.13.1

# ✅ Config icônes (source unique)
flutter_launcher_icons:
  android: true
  windows:
    generate: true
  web:
    generate: true
  image_path: "assets/badiboss_logo.jpg"
  adaptive_icon_background: "#2F5D50"
  adaptive_icon_foreground: "assets/badiboss_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/badiboss_logo.jpg
